config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'
  
  resources :restaurants, only: [:index, :show, :new, :create ] do
    resources :reviews, only: [:show, :create, :destroy]
    resources :reservations, only: [:index, :new, :create]
  end

  resources :users, only: [ :show, :new, :create]
  resources :reservations, only: [:destroy]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base

  has_many :restaurants

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  belongs_to :user
  belongs_to :restaurant

  validate :less_than_max_capacity

  protected

  def less_than_max_capacity
    if !self.restaurant.available?(self.date, self.time, self.party_size)
      errors.add(:base, "Sorry, too many people!")
    end
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_many :reservations
  has_many :users, through: :reservations
  belongs_to :cuisine
  has_many :reviews
  has_many :users, through: :reviews
  belongs_to :user

  def available?(date, time, party_size)
    party_size <= available_capacity(date, time)
  end

  private

  def available_capacity(date, time)
    self.capacity - self.reservations.where(date: date, time: time).sum(:party_size)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reservations
  has_many :restaurants, through: :reservations
  has_many :reviews, through: :restaurants
  has_many :owned_restaurants, class_name: "Restaurant"

  validates :first_name,:last_name,:email,:phone_number, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_url
    end
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :load_restaurant, except: [:destroy]
  before_action :ensure_logged_in, only: [:create, :destroy]

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user = current_user

    if @reservation.save
      UserMailer.reservation_email(current_user, @reservation).deliver_now
      redirect_to restaurants_url, notice: "reservation created successfully"
    else
      render "reservations/new"
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to user_path(:id), notice: "Reservation deleted successfully"
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :restaurant_id, :date, :time, :party_size)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :ensure_logged_in, only: [:create, :new]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant =Restaurant.new
  end

  def create
    @user= User.find(session[:user_id])
    if @user.is_owner
      @restaurant = @user.owned_restaurants.build(restaurant_params)
      if @restaurant.save
        redirect_to restaurants_url, notice: "Thank you for Signing up"
      else
        render "new"
      end
    else
      redirect_to  restaurants_url, notice: "you have to be an owner to create a restaurant"
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @new_review = @restaurant.reviews.build
  end

  

  private
  def restaurant_params
    params.require(:restaurant).permit(:name,:cuisine_id,:address,:capacity ,:phone_number,:user_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_restaurant
  before_action :ensure_logged_in, only: [ :create, :destroy ]

  def show
    @review = Review.find( params[ :id ] )
  end

  def create
    @review = @restaurant.reviews.build( review_params )
    @review.user = current_user

    if @review.save
      redirect_to restaurant_path(params[:restaurant_id]), notice: "Review created successfully"
    else
      render "restaurants/show"
    end
  end

  def destroy
    @review = Review.find( params[ :id ])
    @review.destroy
  end

  private

  def review_params
    params.require( :review ).permit( :comment, :restaurant_id, :rating )
  end

  def load_restaurant
    @restaurant = Restaurant.find( params[ :restaurant_id ] )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, notice: "You're logged in."
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        UserMailer.welcome_email(@user).deliver_now
        redirect_to restaurants_url, notice: "Thank you for Signing up"
      else
        render "new"
      end
    end


private
  def user_params
    params.require(:user).permit(:email, :first_name , :last_name , :phone_number, :is_owner  , :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>

</body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/new.html.erb
<nav class="navbar navbar-inverse" role="navigation">

    <div class="navbar-header">
      <a class="navbar-brand" href="#">Seat<i>Yourself</i></a>
    </div>
  <div>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="/restaurants">Home</a></li>
        <% if current_user %>
        <li><a href="">Signed in as <%= current_user.email %></a></li>
        <li><a href="">|</a></li>
        <li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %></li>
        <% end %>

      <li>
        <% if current_user %>
          <%= link_to "My Profile", user_path(:id) %>
        <% end %>
      </li>
    </ul>
</div>
</nav>


<div class="reservations-page">
  <div class="container">
  <h1>Create a Reservation for: <h1><strong><%= "#{@restaurant.name}" %></strong></h1></h1>


<div class="container" id="reservation-form">
  <%= form_for([@restaurant, @reservation]) do |f| %>
    <%if @reservation.errors.any? %>
      <div class= "error_messages">
        <h2>  Missing infomation </h2>
        <ul>
          <% @reservation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
    </br>
      <%= f.label :date %><br/>
      <%= f.date_field :date %>
    </div>

    <div class= "field">
      <%= f.label :time %><br/>
      <%= f.time_select :time %>
    </div>

    <div class = "field">
      <%= f.label :party_size %><br/>
      <%= f.select :party_size, [['1', 1], ['2', 2], ['3',3],['4',4],['5',5],['6',6],["10",10]] %>
    </div>

    <div class="actions"></br>
       <%= f.submit %>
    </div>

  <% end %>
</div>
  </div>
</div>

app/views/restaurants/index.html.erb
<!-- Navigation Bar: -->

<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Seat<i>Yourself</i></a>
  </div>
  <div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/restaurants">Home</a></li>
      <% if current_user %>
        <li><a href="">Signed in as <%= current_user.email %></a></li>
        <li><a href="">|</a></li>
        <li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
      <% else %>
        <li><%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %></li>
      <% end %>
      <% if current_user %>
        <li><%= link_to "My Profile", user_path(:id) %></li>
      <% end %>
    </ul>
  </div>
</nav>

<!-- Main Body Content: -->

<div class="jumbotron">
  <img src="http://calvertjournal.com/images/uploads/articles/02-13/Oldich/_large_crop/pa_calvert_oldrich_17.jpg">
  <h2>Join Billions on the Journey to Self-Seating</h2>
</div>
<div class="container">
<h1>Choose which restaurant you'd like to reserve a seat at:</h1>
</div>

<div class="container">
  <div class="content">
    <table class="table-hover table-responsive">
      <colgroup>
        <col width="30%">
        <col width="40%">
        <col width="30%">
      </colgroup>
    <% @restaurants.each do |restaurant| %>
        <tr>
          <td id="rest-image"> <a href="restaurants/<%=restaurant.id%>"><img src="http://placekitten.com/350/350" style="padding-bottom: 10px"></a> </td>
          <td> <a href="restaurants/<%=restaurant.id%>"><h2 id="rest-name"><%= "#{restaurant.name}" %></h2></a></td>
          <td><h2 id="rest-contact"><%= "#{restaurant.address}" %></br></br><%= "#{restaurant.phone_number}" %></h2></td>
       </tr>
     <% end %>
    </table>
  </div>
</div>


<div id="footer">
  <div class="container">
     <p class="text-muted credit" style="font-weight: bold; text-decoration: underline">SeatYourself 2016</p>
     <p class="text-muted credit">Arnold Redoblado</p>
     <p class="text-muted credit">Peter La</p>
     <p class="text-muted credit">Francis Gallo</p>
     <p class="text-muted credit">Mike Thai</p>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container" id="title">
<h1>Creating a Restaurant!</h1>
</div >

<div class="container" id="form">
<%= form_for @restaurant do |f| %>
<%if @restaurant.errors.any? %>
    <div class= "error_messages">
      <h2>  Missing infomation </h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  <% end %>



<%= form_for @restaurant do |f| %>
    <div class="field">
      <%= f.label :name %><br/>
      <%= f.text_field :name %></br>
    </div>

    <div class= "field">
    </br><%= f.label :phone_number %><br/>
      <%= f.text_field :phone_number %></br>
    </div>

    <div class = "field">
      </br><%= f.label :address%><br/>
      <%= f.text_field :address %>
    </div>

    <div class ="field">
    </br><%= f.label :capacity %><br/>
      <%= f.number_field :capacity , min:10, max:100 %>
    </div>

    <div class= "field">
    </br><%= f.label :Cuisine_Type %><br/>
    <%=f.select :cuisine_id, [['Mexican', 1], ['Chinese', 2], ['Japanese',3]] %>

   <div class="actions">
     </br><%= f.submit %>
  </div>
<% end %>
</div>

app/views/restaurants/show.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Seat<i>Yourself</i></a>
  </div>
  <div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/restaurants">Home</a></li>
      <% if current_user %>
        <li><a href="">Signed in as <%= current_user.email %></a></li>
        <li><a href="">|</a></li>
        <li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
      <% else %>
        <li><%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %></li>
      <% end %>
      <% if current_user %>
        <li><%= link_to "My Profile", user_path(:id) %> , <%= link_to "Create Restaurant", new_restaurant_path %>
      <% end %>
        </li>
    </ul>
  </div>
</nav>


<div class="restaurant-show">

  <div class="container">
    <h1><%= "#{@restaurant.name}" %></h1>
    <h2><%= link_to "Make a Reservation!", new_restaurant_reservation_url( @restaurant.id )%></h2>
    <table class="table">
    <tr>
        <td><img src="http://elrestaurante.com/downloads/756/download/bitblt-640xNone-62948b14a3b4192e529d5aa419e0002a1e776b5e/LambCampechenaTacos.png?cb=706fc1b8f60098200302bfff3101eef7"></td>
        <td id="rest-contact-info">
        <h3><%= "#{@restaurant.address}" %></h3>
        <h3><%= "#{@restaurant.phone_number}" %></h3></td>
    </tr>
    </table></br></br>
  </div>

  <div class="container" id="reviews">
  <h2>Reviews for <%= @restaurant.name %>:</h2>
  <% @restaurant.reviews.order(:created_at).reverse.each do |review| %>
    <p>
      <%= review.comment %></br>Rating: <%= review.rating %>

      <% if review.user != nil %>
      <em> </br>by <%= review.user.first_name %> </em>
    </br>Added on: <%= review.created_at %>
      <% end %>
      </p>
      <% end %>


    <% if current_user %>

    <%= form_for([@restaurant, @new_review]) do | f | %>
      <% if @new_review.errors.any? %>
        <h2><%= pluralize( @new_review.errors.count, "error" ) %>
            prohibited this review from being saved:</h2>
        <ul>
            <% @new_review.errors.full_messages.each do | msg | %>
            <li>
                <% msg %>
            </li>
            <% end %>
        </ul>
      <% end %>
      <p></br></br>
          <%= f.label :comment %></p>
          <p><%= f.text_area :comment %></br>

      </p>

      <p>
        <%= f.radio_button(:rating , 1) %>
        <%= f.label(:rating , "1") %>
        <%= f.radio_button(:rating , 2) %>
        <%= f.label(:rating , "2") %>
        <%= f.radio_button(:rating , 3) %>
        <%= f.label(:rating ,"3") %>
        <%= f.radio_button(:rating , 4) %>
        <%= f.label(:rating, "4") %>
        <%= f.radio_button(:rating, 5) %>
        <%= f.label(:rating, "5" ) %>
      </p></br>

      <p>
          <%= f.submit %>
      </p>
    <% end %>
    <% else %>
    <p>
        Please
        <%= link_to "log in", new_session_path %>
        to add a review.
    </p>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<p id="back"><%= link_to "Back", restaurants_url %></p>

<div class="container" id="title">
<h1>Sign Up!</h1>
</div >

<div class="container" id="form">
<%= form_for @user do |f| %>
<%if @user.errors.any? %>
    <div class= "error_messages">
      <h2>  Missing infomation </h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  <% end %>

<%= form_for @user do |f| %>
    <div class="field">
      <%= f.label :email %><br/>
      <%= f.email_field :email %></br>
    </div>

    <div class= "field">
      </br><%= f.label :first_name %><br/>
      <%= f.text_field :first_name %></br>
    </div>

    <div class = "field">
      </br><%= f.label :last_name %><br/>
      <%= f.text_field :last_name %>
    </div>

    <div class ="field">
    </br><%= f.label :phone_number %><br/>
      <%= f.text_field :phone_number %>
    </div>

    <div class ="field">
    </br><%= f.label :I_Am_An_Owner %><br/>
      <%=f.check_box :is_owner %>
    </div>

    <div class="field">
     </br><%= f.label :password %><br/>
     <%= f.password_field :password %>
   </div>

   <div class="field">
     </br><%= f.label :password_confirmation %><br/>
     <%= f.password_field :password_confirmation %>
   </div>

   <div class="actions">
     </br><%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-inverse" role="navigation">

    <div class="navbar-header">
        <a class="navbar-brand" href="#">Seat<i>Yourself</i>
        </a>
    </div>
    <div>

        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="/restaurants">Home</a>
            </li>
            <% if current_user %>
            <li>
                <a href="">Signed in as
                    <%= current_user.email %></a>
            </li>
            <li>
                <a href="">|</a>
            </li>
            <li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
        <% else %>
            <li><%= link_to "Log in", new_session_path %>
                or
                <%= link_to "Sign up", new_user_path %></li>
            <% end %>
            <li>
                <% if current_user %>
                <%= link_to "My Profile", user_path(:id) %>
                <% end %>
            </li>
        </ul>
    </div>
</nav>

<div class="reservations-page">
    <h1 style="text-align: left; margin-left: 20px; margin-bottom: 20px; text-decoration: underline">My Profile:</h1>

    <div class="container">
        <table class="table" id="profile">

            <tr>
                <td>Name:</td>
                <td><%= current_user.first_name %>
                    <%= current_user.last_name %></td>
            </tr>

            <tr>
                <td>Phone Number:</td>
                <td><%= current_user.phone_number %></td>
            </tr>

            <tr>
                <td>Email:</td>
                <td><%= current_user.email %></td>
            </tr>

            <tr>
                <td>
                    Owner?</td>
                <td><%= current_user.is_owner %></td>
            </tr>
        </table>
    </div>

  <div id="my-restaurants">
    <h4>My Restaurants:</h4>
    <% current_user.owned_restaurants.each do |restaurant| %>
    <li><%= restaurant.name %></li>
    <% end %>
</div>

<div id="my-reservations">
<h4>My Reservations:</h4>
<% current_user.reservations.each do |reservation| %>
  <ul>
    <li><%= reservation.restaurant.name %></li>
    <li><%= reservation.date %> <%= reservation.time %></li>
    <li>Party of <%=reservation.party_size %></li>
    <li></br><% if current_user %>
      <%= link_to "Delete Reservation", reservation_path(reservation.id), method: :delete, data: {confirm:  "Are you sure you want to delete this reservation?"} %></li>
    <% end %>
  <% end %>
  </ul>
</div>
>>>>>>> enter-bootstrap